# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ACE/TAO clone
email: mesnierp@ociweb.com
description: > # this means to ignore newlines until "baseurl:"
  This is Phi's working copy of the DOC Group's version of ACE TAO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theaceorb.com" # the base hostname & protocol for your site
# twitter_username:
github_username:  pmesnier

# Build settings
markdown: kramdown
